{% set version = "2.0.4" %}

package:
  name: glad2
  version: {{ version }}

source:
  url: https://github.com/Dav1dde/glad/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 02629644c242dcc27c58222bd2c001d5e2f3765dbbcfd796542308bddebab401
  patches:
    - 0001-cmake.patch

build:
  number: 1

outputs:
  - name: glad2
    build:
      noarch: python
      entry_points:
        - glad = glad.__main__:main
      script: python -m pip install . --no-deps -vv

    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - jinja2
      run_constrained:
        - {{ pin_subpackage('glad2-cmake', exact=True) }}

    test:
      imports:
        - glad
      commands:
        - glad --help

  - name: glad2-cmake
    script: install_cmake.sh  # [unix]
    script: install_cmake.bat # [win]

    test:
      commands:
        - test -f $PREFIX/lib/cmake/Glad/GladConfig.cmake                      # [unix]
        - if not exist %LIBRARY_LIB%\\lib\\cmake\\Glad\GladConfig.cmake exit 1 # [win]

    about:
      summary: CMake package for Glad.

about:
  home: https://github.com/Dav1dde/glad
  license: MIT
  license_file: LICENSE
  summary: GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.

extra:
  recipe-maintainers:
    - traversaro
