{% set name = "glad2" %}
{% set version = "2.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Dav1dde/glad/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 02629644c242dcc27c58222bd2c001d5e2f3765dbbcfd796542308bddebab401

build:
  number: 0
  entry_points:
    - glad = glad.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - jinja2

test:
  imports:
    - glad
  commands:
    - glad --help

about:
  home: https://github.com/Dav1dde/glad
  license: MIT
  license_file: LICENSE
  summary: GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.

extra:
  recipe-maintainers:
    - cNoNim
    - traversaro
