{% set name = "glad" %}
{% set version = "2.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Dav1dde/glad/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0326d59b1ccf8ccae1fface5bfb71bec1bb41fbe2341e722b31f6acac3068aeb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
    - python

test:
  commands:
    - test -f ${PREFIX}/include/glad/glad.h  # [not win]
    - test -f ${PREFIX}/lib/libglad.so  # [linux]
    - test -f ${PREFIX}/lib/libglad.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\glad\\glad.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\glad.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\glad.dll exit 1  # [win]

about:
  home: https://github.com/Dav1dde/glad
  license: MIT
  license_file: LICENSE
  summary: GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.

extra:
  recipe-maintainers:
    - traversaro
