{% set version = "2.0.4" %}

package:
  name: glad2
  version: {{ version }}

source:
  url: https://github.com/Dav1dde/glad/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 02629644c242dcc27c58222bd2c001d5e2f3765dbbcfd796542308bddebab401
  patches:
    - 0001-findpython.patch
    - 0002-cmake.patch

build:
  number: 2

outputs:
  - name: glad2
    build:
      noarch: python
      skip: True  # [not linux64]
      entry_points:
        - glad = glad.__main__:main
      script: python -m pip install . --no-deps -vv

    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
        - jinja2

    test:
      imports:
        - glad
      commands:
        - glad --help

  - name: glad2-cmake
    build:
      skip: False

    requirements:
      # dummy build env to avoid EnvironmentLocationNotFound on win
      build:     # [win]
        - cmake  # [win]
      run:
        - {{ pin_subpackage('glad2', exact=True) }}

    script: install_cmake.sh   # [unix]
    script: install_cmake.bat  # [win]

    test:
      requires:
        - cmake
      source_files:
        - CMakeLists.txt
      commands:
        - cmake -B build

    about:
      home: https://github.com/Dav1dde/glad
      license: MIT
      license_file: LICENSE
      summary: CMake package for glad2.
      description: |
        Example of use:
        ```cmake
        find_package(Glad CONFIG REQUIRED)
        glad_add_library(glad_gl_core_mx_33 REPRODUCIBLE MX API gl:core=3.3)
        ```
        and link `glad_gl_core_mx_33` to target

about:
  home: https://github.com/Dav1dde/glad
  license: MIT
  license_file: LICENSE
  summary: GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs.

extra:
  recipe-maintainers:
    - cNoNim
    - traversaro
